import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "./session";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ...props
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContext>
        <body className={inter.className}>
          {" "}
          <div className="grid-rows-2 fixed">
            <div className="flex">
              <Navbar />
            </div>
          </div>
          <div className="grid-rows-10">
            <div>{children}</div>
          </div>
        </body>
      </AuthContext>
    </html>
  );
}
